default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogdeploy_development

test:
  <<: *default
  database: blogdeploy_test

# SIMPLIFIED PRODUCTION CONFIG FOR RENDER
production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
